### ISSUE TITLE
/ontime "pseudo"

### ISSUE THREAD

**Issue by PapiCapi** [Aeliios/OnTimeModifier#1]
J'ai pas encore testé mais de ce que je vois tu as tout fait sur le ontime top.
Je crois pas te l'avoir dit donc mybad mais lorsque tu fais /ontime "pseudo", tu vois si la personne est co et depuis combien de temps donc à modifier aussi dans l'idéal
![image](https://user-images.githubusercontent.com/49530141/109388063-1475e480-7905-11eb-9b00-002e279a0e7a.png)

**Comment by Aeliios** [comment]
Les joueurs n'ont pas accès à cette commande.
